# Generated by Django 2.0.2 on 2020-05-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=255)),
                ('prjtitle', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('descr', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('envt', models.CharField(max_length=255)),
                ('prjlogo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
