# Generated by Django 2.0.2 on 2020-05-10 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexp',
            name='fromdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexp',
            name='todate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
