# Generated by Django 2.0.2 on 2020-05-10 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0002_auto_20200510_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexp',
            old_name='client',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='workexp',
            old_name='body',
            new_name='Decription',
        ),
        migrations.RenameField(
            model_name='workexp',
            old_name='descr',
            new_name='Environments',
        ),
        migrations.RenameField(
            model_name='workexp',
            old_name='fromdate',
            new_name='FromDate',
        ),
        migrations.RenameField(
            model_name='workexp',
            old_name='envt',
            new_name='OraganizationName',
        ),
        migrations.RenameField(
            model_name='workexp',
            old_name='prjlogo',
            new_name='ProjectLogo',
        ),
        migrations.RenameField(
            model_name='workexp',
            old_name='orgname',
            new_name='ProjectTitle',
        ),
        migrations.RenameField(
            model_name='workexp',
            old_name='prjtitle',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='workexp',
            old_name='todate',
            new_name='toDate',
        ),
        migrations.RemoveField(
            model_name='workexp',
            name='role',
        ),
        migrations.AddField(
            model_name='workexp',
            name='Responsibilities',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
